#!/bin/env lua
if not arg[1] then
    error('\nUsage: ' .. arg[0] .. ' [-v] [--compat] [format] game.ink\n')
end

local verbose = false
local compatMode = false
if arg[1] == '-v' then
    verbose = true
    table.remove(arg, 1)
end
if arg[1] == '--compat' then
    compatMode = true
    table.remove(arg, 1)
end

local logging = require('pink.logging')
if compatMode then
    logging.compat = true
end

local formatter = require('pink.formatter')
local runtime = require('pink.runtime')
local load = require('pink.loader')

if verbose then
    logging.debugEnabled = true
end

local format = false
if arg[1] == 'format' then
    format = true
    table.remove(arg, 1)
end

local filename = arg[1]

if format then
    print(formatter(load(filename)))
    return
end

local story = runtime(load(filename))
while true do
    while story.canContinue do
        io.write(story.continue())
        if #story.currentTags > 0 then
            print('# tags: ' .. table.concat(story.currentTags, ', ')) -- TODO configurable
        end
    end
    if #story.currentChoices == 0 then
        break
    end
    for i = 1, #story.currentChoices do
        print(i .. ': ' .. story.currentChoices[i].text)
    end
    io.write('?> ')
    local answer = tonumber(io.read('*number'))
    if not answer then
        error('missing answer')
    end
    if not answer or answer > #story.currentChoices then
        error('invalid answer: ' .. tostring(answer))
    end
    story.chooseChoiceIndex(answer)
end
